### ISSUE TITLE
文件名有空格时出错

### ISSUE THREAD

**Issue by the0demiurge** [petronny/pinyin-completion#10]
![image](https://user-images.githubusercontent.com/11363529/39659270-5a082d20-5057-11e8-8ca1-f6c3a521b094.png)

另外请求增加fish-shell的支持

**Comment by Freed-Wu** [comment]
i have test it in zsh and bash. it looks like this bug only happened in bash not zsh.

**Comment by Freed-Wu** [comment]
@the0demiurge can you try #13? now it should work for both bash and zsh.
