### ISSUE TITLE
zsh extra qoute

### ISSUE THREAD

**Issue by leoleoasd** [petronny/pinyin-completion#17]
should replace 
```
reply=(${(q)$(pinyin-comp x-d $*)} $*)
```
with
```
reply=(${$(pinyin-comp x-d $*)} $*)
```
to avoid outputs being escaped twice:

```
(base) (win/x64)  ➜  ~/winhome/Downloads ls zr<TAB>
\'自然语言处理结课报告封面.docx\'  \'自然语言处理课程结课作业.docx\'  zr
(base) (win/x64)  ➜  ~/winhome/Downloads ls \'自然语言处理结课报告封面.docx\' # should be '自然语言处理结课报告封面.docx'
```

**Comment by Freed-Wu** [comment]
`${(q)...}` is needed, because filenames can contains whitespace or other special characters.

![image](https://github.com/petronny/pinyin-completion/assets/32936898/a880a2e1-90c8-4b6c-86f1-38a38458bab9)
