### ISSUE TITLE
Question: 多于一个匹配的中文目录补全时，会增加一个不存在的候选项

### ISSUE THREAD

**Issue by Firef0x** [petronny/pinyin-completion#3]
@petronny ，您好！

首先感谢您接手此项目并将此软件带到 [[archlinuxcn]](https://github.com/archlinuxcn/repo/tree/master/pinyin-completion) 仓库。 :rose: 

在此我冒昧报告一个问题：

使用 `Zsh` 配合此软件进行拼音补全时，当出现多于一个匹配的中文目录补全时，按 `Tab` 键不知为何会增加一个候选项，内容为所有匹配中文目录连接在一起的字符串（并不存在名字为此字符串的目录），见图：

![cd3](https://cloud.githubusercontent.com/assets/2487841/5753313/f622c6f4-9cc1-11e4-9cf9-078d5f72ac1f.png)

如何去掉这一个多余且不存在的候选项？

在此祝您新年愉快！ :gift: 

此致！ :bow:

**Comment by petronny** [comment]
这个不应该算一个bug. 最后那个是算在expand里面的all expansions里面的。
![img](http://7sbplw.com1.z0.glb.clouddn.com/screenshot-20150115_154655.png)

这个commit[03f7ea2](https://github.com/petronny/pinyin-completion/commit/03f7ea2b3b175bd0027e8cd844e23f485adbaf96)把all expansions删了但是还是不对：

当只有一个补全项时，
expansions为空，all expansions里面有东西

所以如果把all expansions去了，只有一个补全项的就补不出来了

解决办法有2种：

1. 直接把original写到补全项中去，这样如果有补全肯定不少于2个，然后把all expansions去了就完了
2. 恢复成原来那样，不过把all expansions挪到最后就完了

你喜欢哪个？

**Comment by Firef0x** [comment]
@petronny ，您好！

个人觉得第一种解决办法比较合理，当然也不排除有其他用户喜欢第二种办法。如果您愿意的话也可以都实现，并提供一个选项或者环境变量供用户们选择采用那种办法。

此致！ :bow:
