### ISSUE TITLE
命令按tab补全时的问题

### ISSUE THREAD

**Issue by Kzinux** [petronny/pinyin-completion#6]
又打扰了，刚才又发现一个alias的命令的问题。

我zshrc里有一些alias的命令，其中一个是mplayer的：alias mplayertext='mplayer -vo aa' 。
当我输入mplayertext后按tab正常的应该是显示当前目录的文件和子目录，但是却补全了当前的alias命令mplayertest。如下图：
![alias](https://cloud.githubusercontent.com/assets/7030257/6096956/d9820650-afe4-11e4-9f93-3fe7add7759b.gif)

还有另一种情况，在zshrc里alias一个比mplayertext更长的命令，比如：alias mplayertexttext='mplayer -vo aa' 。
这时再输入mplayertext按tab就正常显示目录和文件。如下图：
![alias2](https://cloud.githubusercontent.com/assets/7030257/6097007/1a95c5b2-afe7-11e4-929d-e30aa6785ddb.gif)

alias的命令补全时只有一个候选就会出现问题。

**Comment by Kzinux** [comment]
才发现不只alias的命令，普通命令也有这个问题。在输入命令后多按一下空格，或者用Backspace键删掉tab补全的空格再重新输入空格补全就正常了。
![space](https://cloud.githubusercontent.com/assets/7030257/6097093/0bc9eff6-afea-11e4-8780-32c226be0fe8.gif)

**Comment by petronny** [comment]
__我这里不能重现你所说的情况__
我新添加了alias mplayertext='mplayer -vo aa' 
然后我mplay<tab>可以补全出mplayer和mplayertext
无论我是手动选mplayertext还是打mplayert<tab>补全出的mplayertext
mplayertext都可以正常补全media file类型和url类型

### 猜想：是否和_force_rehash()函数相关？
我装了grml-zsh-config，里面自带了大量函数，包括_force_rehash()。
我猜测可能和_force_rehash()函数相关
如果你的zsh没有_force_rehash()，尝试添加一个，或者把[shell/pinyin-comp.zsh](https://github.com/petronny/pinyin-completion/blob/master/shell/pinyin-comp.zsh)中所有的_force_rehash_pinyin_comp替换为_force_rehash

**Comment by Kzinux** [comment]
force_rehash()添加是安装grml-zsh-config吗？我装了也试了替换没解决问题。

不能重现我就怀疑是我的zshrc的问题，把补全相关的自定义设置删除后问题就解决了。还不清楚具体具体那些代码，当初复制别人的，刚才一下删了一段就正常了，我再慢慢找。

多谢petronny热心解答，找到了再反馈下。

**Comment by Kzinux** [comment]
找到了，只要把下面这一句删掉就正常了。
zstyle ':completion:*:*:default' force-list always
不知道干嘛用的，删掉也没觉得有什么变化。

**Comment by Firef0x** [comment]
@Kzinux @petronny ，您好！

我认为跟 `_force_rehash` 函数被重命名的关系不大，我没有安装 `grml-zsh-config` ，尝试全文搜索了整个文件系统的文件，只有 `pinyin-completion` 相关的文件搜索到了 `_force_rehash` 的字符串，所以我认为将 `_force_rehash` 函数重命名（见 https://github.com/petronny/pinyin-completion/pull/4 ）在目前看来是安全的。

此致！ :bow:
