### ISSUE TITLE
拼音补全后符号没有转义

### ISSUE THREAD

**Issue by Kzinux** [petronny/pinyin-completion#7]
文件名中包含中括号的补全后中括号没有转义，如下图：
![fhzy](https://cloud.githubusercontent.com/assets/7030257/6101715/d96329a4-b063-11e4-85af-a466de97b1c3.gif)

**Comment by petronny** [comment]
`[`和`]`已经添加了。
其实还有很多的字符没有转义，只不过不太常用，我就没管。
> 哪来的那么多奇奇怪怪的文件名。。
