### ISSUE TITLE
../经过拼音扩展后变成了.

### ISSUE THREAD

**Issue by Kzinux** [petronny/pinyin-completion#9]
环境：
archlinux
grml-zsh-config 0.11.2-1
zsh 5.0.7-1
zsh-completions 0.12.0-1

问题描述：当前文件夹上一层有一个文件夹‘图片’，当输入命令进入‘图片’文件夹时，'cd ../tp'扩展后变成了'.图片'。

排除zshrc问题，用下面的最小化的zshrc测试过了。
autoload -U compinit
compinit
#Zsh pinyin completion
source /usr/share/pinyin-completion/shell/pinyin-comp.zsh

附图：
![pycl](https://cloud.githubusercontent.com/assets/7030257/7219585/9246d64a-e6d9-11e4-9901-1bb30a61ba9c.gif)

**Comment by petronny** [comment]
确认如此。明天尝试修复。

**Comment by Kzinux** [comment]
好巧。
多谢了。

**Comment by petronny** [comment]
看了一下，原来就直接把./替换成""了。
现在只把"^./"替换成""。
不过中间的./就替换不了了。比如.././tp(虽然那个./有点多余。。)

**Comment by Kzinux** [comment]
中间的./好怪异。
升级到52.dd59b13-1，确认修复。
